In [1]:
# 오른쪽 위에 연필이 있으면 에딧모드, 아무것도 없으면 커맨드 모드
# 커맨드모드는 셀을 복사, 붙여넣기 같은것들을 할 수 있고,
# 에딧 모드는 키보드에 뭔가 치고 셀에 입력하는 것 
# 여기서 esc를 누르면 커맨드 모드로 돌아간다.
# 커널 - 우리가 실행시킨 언어를 실행하는 엔진?

In [ ]:
# 셀 실행 시킨 뒤 아래에 셀 추가하는 단축키는 알트 엔터
# 다음 셀이 있으면 다음셀로 넘어가고, 없으면 셀을 만들어주는 키 쉬프트 엔터
# 메뉴에서 Cell - Run All을 누르면 모든 셀을 실행
# 새로운 세션을 만들고자하면(모든 결과물을 안보이게 하는 방법)
# Cell - Restart and clear output

In [ ]:
# 주피터는 실행되는 순서대로가 아니라, 왼쪽에 실행된 순서대로 인식한다.
# 하지만 반드시 순서대로 입력하는 것을 권장.

In [ ]:
# 메뉴바 아래에 Code 부분을 Markdown으로 바꾸면 셀에서 글씨를 쓰는 모드로 바뀐다.
# #샵의 개수로 글씨 크기를 조절한다(하나가 제일 크다)
# **이렇게** 두껍게 쓰고(혹은 __이렇게__), *이렇게* 날려쓴다.
# list item 1 을 통해서 리스트도 사용 가능

In [2]:
# print 출력, print 없이 출력하는 결과물이 다를 수 있다.
# 특히, pandas를 통해서 데이터프레임을 나타낼 때 print를 안써야 더 이쁘게 나타난다.

"python\nprint('hello python')\n\n\n"

# numpy

In [2]:
import numpy

In [4]:
array1 = numpy.array([1,2,3,4,5,6,7,8,9,10,11])

In [5]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
type(array1)
# n demantional array 
# n차원 array라는 의미

numpy.ndarray

In [7]:
array1.shape
# 1차원일 경우는 요소의 개수만 나옴

(11,)

In [10]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 2차원 array
# 행이 3개, 열이 4개인 array

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
array2.shape
# 2차원일 경우는 세로(행), 가로(열) 길이가 나온다.

(3, 4)

In [14]:
array1.size
# array에 몇개의 요소?

11

In [15]:
array2.size
# 3 * 4 해서 12
# 결국 size는 반드시 요소의 개수
# shape는 1차원일 경우만 요소의 개수이고, 나머지는 모두 (행, 렬) 형태가 나타난다.

12

#### 균일한 값으로 생성

In [17]:
array3 = numpy.full(5,7)
# 5개의 요소를 7로 다 채워라

In [20]:
array3
# 확인

array([7, 7, 7, 7, 7])

#### 모두 0으로 채우기 (full 메소드 사용 않고)

In [31]:
array0 = numpy.zeros(6, dtype=int)
# 괄호 안에는 스타일을 붙이는게 정석?

In [32]:
array0

array([0., 0., 0., 0., 0., 0.])

#### 모두 1로 채우기

In [24]:
array_ones = numpy.ones(5, dtype=int)

In [25]:
array_ones

array([1, 1, 1, 1, 1])

#### 랜덤한 값으로 생성
random 이라는 모듈 안에 random이라는 함수 불러오기

In [8]:
array_ran = numpy.random.random(6)
# 정수 랜덤값은 불가?
# numpy.random.randint(6) 으로 가능.

In [9]:
array_ran

array([0.66314543, 0.33877616, 0.25693506, 0.75192393, 0.08540182,
       0.92901202])

#### 연속적인 값으로 생성
numpy의 arange 함수는 range 함수와 유사하다
arrange가 아니라 arange이다. r을 두번 쓰지 말 것.

In [34]:
array_proceed = numpy.arange(6)
# arange(m, n)
# arange(m, n, s)

In [35]:
array_proceed

array([0, 1, 2, 3, 4, 5])