In [2]:
import numpy as np

## 엔화를 원화로 바꾸는 방법
**list를 array로 바꾸는 방법**

In [5]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

yen_array = np.array(revenue_in_yen)
won_array = yen_array * 10.08
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [9]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

yen_array = np.array(revenue_in_yen)
dollar_array = np.array(revenue_in_dollar)

won_array = yen_array * 10.08 + dollar_array * 1138

# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

# numpy 불린 연산
array > 4와 같이 하면, 각 자리에 True or False로 나타난다.
여기에 np.where(array > 4) 처럼 하면 True인 곳의 인덱스를 뽑아내서 array처럼 만든다.
이를 다른 변수에 할당(filter)한다. 이 filter는 true인 곳의 인덱스를 갖는 array이다.
이전에 만들어논 어떤 배열 array1[filter]은 결국 True인 곳의 값을 출력하도록 하는 것.
array1[인덱스] 처럼 하면 해당 값이 나올 수 있다.

In [14]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

yen_array = np.array(revenue_in_yen)
bad_index = np.where(yen_array < 200000)
bad_days_revenue = yen_array[bad_index]


# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

#### 중앙값은 최대값, 최소값, 평균, 분산, 표준편차와 다르게 numpy 자체의 기능이다.

In [16]:


array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

array1.max() # 최댓값 --> numpy array

np.median(array1) # 중앙값 --> numpy


13.5