In [1]:
import numpy as np

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

# 넘파이 만들기

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)

C

array([[0.43282202, 0.35020518, 0.6904048 , 0.0275832 , 0.30744967],
       [0.35925729, 0.60134659, 0.22952988, 0.25036942, 0.4848269 ],
       [0.3809042 , 0.40850947, 0.65921463, 0.55759876, 0.06875786]])

In [6]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A[0][2]

2

In [10]:
# 1.
A = np.array([
    [0, 1, -1],
    [1, 2, 3],
    [2, 1, 0],
    [-1, 2, -4]
])
A

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2, -4]])

In [11]:
B = np.array([
    [0, 2],
    [1, 1],
    [-1, -2]
])
B

array([[ 0,  2],
       [ 1,  1],
       [-1, -2]])

In [12]:
A[1][1]

2

In [14]:
A[3][0]

-1

## 행렬 연산

In [15]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

In [16]:
A

array([[0.14859205, 0.38663934, 0.7602704 ],
       [0.66698291, 0.59523186, 0.89138809],
       [0.42191649, 0.1205946 , 0.17497872]])

In [17]:
B

array([[0.47719578, 0.15097473, 0.73773526],
       [0.80701597, 0.72307682, 0.6062471 ],
       [0.23606332, 0.16937587, 0.22802335]])

In [18]:
A+B

array([[0.62578783, 0.53761407, 1.49800566],
       [1.47399888, 1.31830867, 1.49763519],
       [0.65797981, 0.28997047, 0.40300207]])

In [19]:
5 * A

array([[0.74296027, 1.93319671, 3.80135199],
       [3.33491455, 2.97615929, 4.45694044],
       [2.10958243, 0.60297299, 0.87489359]])

In [20]:
np.dot(A, B)

array([[0.56240358, 0.43077505, 0.51737998],
       [1.00906708, 0.68207555, 1.0561717 ],
       [0.33996459, 0.18053506, 0.42427203]])

### 행렬 곱셈은 골뱅이'@'로도 가능하다.

In [21]:
A @ B

array([[0.56240358, 0.43077505, 0.51737998],
       [1.00906708, 0.68207555, 1.0561717 ],
       [0.33996459, 0.18053506, 0.42427203]])

### 2A는 안되지만, -A는 된다는 점 

In [25]:
-A


array([[-0.14859205, -0.38663934, -0.7602704 ],
       [-0.66698291, -0.59523186, -0.89138809],
       [-0.42191649, -0.1205946 , -0.17497872]])

In [26]:
A

array([[0.14859205, 0.38663934, 0.7602704 ],
       [0.66698291, 0.59523186, 0.89138809],
       [0.42191649, 0.1205946 , 0.17497872]])

In [28]:
A_transpose = np.transpose(A)

In [29]:
A_transpose

array([[0.14859205, 0.66698291, 0.42191649],
       [0.38663934, 0.59523186, 0.1205946 ],
       [0.7602704 , 0.89138809, 0.17497872]])

#### Transpose는 .T로.


In [30]:
A.T

array([[0.14859205, 0.66698291, 0.42191649],
       [0.38663934, 0.59523186, 0.1205946 ],
       [0.7602704 , 0.89138809, 0.17497872]])

In [31]:
# 단위행렬
I = np.identity(3)

In [34]:
# 역행렬
A_inverse = np.linalg.pinv(A)

#### linalg.pinv 메소드의 재밌는 점은

역행렬이 구해지지 않는 행렬에서도

역행렬이 없음에도 역행렬과 동일한 효과를 내주는 가장 근사한 값을 리턴하는 것

In [38]:
# 둘을 곱해서 단위행렬이 나온다면, 역행렬이 되는 것.
# 소수0의 오차문제를 고려할 것.
A @ A_inverse

array([[ 1.00000000e+00, -2.05453028e-15,  2.06717708e-15],
       [ 1.68995041e-15,  1.00000000e+00,  2.22149054e-15],
       [ 1.24100340e-15, -1.72204359e-15,  1.00000000e+00]])